[package]
edition.workspace = true
name = "mlambda"
version = "0.0.1"

[dependencies]
http = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = "0.1.17"
