#[cfg(feature = "aws_accessanalyzer")]
pub mod accessanalyzer;
#[cfg(feature = "aws_acmpca")]
pub mod acmpca;
#[cfg(feature = "aws_aiops")]
pub mod aiops;
#[cfg(feature = "aws_amazonmq")]
pub mod amazonmq;
#[cfg(feature = "aws_amplify")]
pub mod amplify;
#[cfg(feature = "aws_amplifyuibuilder")]
pub mod amplifyuibuilder;
#[cfg(feature = "aws_apigateway")]
pub mod apigateway;
#[cfg(feature = "aws_apigatewayv2")]
pub mod apigatewayv2;
#[cfg(feature = "aws_appconfig")]
pub mod appconfig;
#[cfg(feature = "aws_appflow")]
pub mod appflow;
#[cfg(feature = "aws_appintegrations")]
pub mod appintegrations;
#[cfg(feature = "aws_applicationautoscaling")]
pub mod applicationautoscaling;
#[cfg(feature = "aws_applicationinsights")]
pub mod applicationinsights;
#[cfg(feature = "aws_applicationsignals")]
pub mod applicationsignals;
#[cfg(feature = "aws_appmesh")]
pub mod appmesh;
#[cfg(feature = "aws_apprunner")]
pub mod apprunner;
#[cfg(feature = "aws_appstream")]
pub mod appstream;
#[cfg(feature = "aws_appsync")]
pub mod appsync;
#[cfg(feature = "aws_apptest")]
pub mod apptest;
#[cfg(feature = "aws_aps")]
pub mod aps;
#[cfg(feature = "aws_arcregionswitch")]
pub mod arcregionswitch;
#[cfg(feature = "aws_arczonalshift")]
pub mod arczonalshift;
#[cfg(feature = "aws_athena")]
pub mod athena;
#[cfg(feature = "aws_auditmanager")]
pub mod auditmanager;
#[cfg(feature = "aws_autoscaling")]
pub mod autoscaling;
#[cfg(feature = "aws_autoscalingplans")]
pub mod autoscalingplans;
#[cfg(feature = "aws_b2bi")]
pub mod b2bi;
#[cfg(feature = "aws_backup")]
pub mod backup;
#[cfg(feature = "aws_backupgateway")]
pub mod backupgateway;
#[cfg(feature = "aws_batch")]
pub mod batch;
#[cfg(feature = "aws_bcmdataexports")]
pub mod bcmdataexports;
#[cfg(feature = "aws_bedrock")]
pub mod bedrock;
#[cfg(feature = "aws_bedrockagentcore")]
pub mod bedrockagentcore;
#[cfg(feature = "aws_billing")]
pub mod billing;
#[cfg(feature = "aws_billingconductor")]
pub mod billingconductor;
#[cfg(feature = "aws_budgets")]
pub mod budgets;
#[cfg(feature = "aws_cases")]
pub mod cases;
#[cfg(feature = "aws_cassandra")]
pub mod cassandra;
#[cfg(feature = "aws_ce")]
pub mod ce;
#[cfg(feature = "aws_certificatemanager")]
pub mod certificatemanager;
#[cfg(feature = "aws_chatbot")]
pub mod chatbot;
#[cfg(feature = "aws_cleanrooms")]
pub mod cleanrooms;
#[cfg(feature = "aws_cleanroomsml")]
pub mod cleanroomsml;
#[cfg(feature = "aws_cloud9")]
pub mod cloud9;
#[cfg(feature = "aws_cloudformation")]
pub mod cloudformation;
#[cfg(feature = "aws_cloudfront")]
pub mod cloudfront;
#[cfg(feature = "aws_cloudtrail")]
pub mod cloudtrail;
#[cfg(feature = "aws_cloudwatch")]
pub mod cloudwatch;
#[cfg(feature = "aws_codeartifact")]
pub mod codeartifact;
#[cfg(feature = "aws_codebuild")]
pub mod codebuild;
#[cfg(feature = "aws_codecommit")]
pub mod codecommit;
#[cfg(feature = "aws_codeconnections")]
pub mod codeconnections;
#[cfg(feature = "aws_codedeploy")]
pub mod codedeploy;
#[cfg(feature = "aws_codeguruprofiler")]
pub mod codeguruprofiler;
#[cfg(feature = "aws_codegurureviewer")]
pub mod codegurureviewer;
#[cfg(feature = "aws_codepipeline")]
pub mod codepipeline;
#[cfg(feature = "aws_codestar")]
pub mod codestar;
#[cfg(feature = "aws_codestarconnections")]
pub mod codestarconnections;
#[cfg(feature = "aws_codestarnotifications")]
pub mod codestarnotifications;
#[cfg(feature = "aws_cognito")]
pub mod cognito;
#[cfg(feature = "aws_comprehend")]
pub mod comprehend;
#[cfg(feature = "aws_config")]
pub mod config;
#[cfg(feature = "aws_connect")]
pub mod connect;
#[cfg(feature = "aws_connectcampaigns")]
pub mod connectcampaigns;
#[cfg(feature = "aws_connectcampaignsv2")]
pub mod connectcampaignsv2;
#[cfg(feature = "aws_controltower")]
pub mod controltower;
#[cfg(feature = "aws_cur")]
pub mod cur;
#[cfg(feature = "aws_customerprofiles")]
pub mod customerprofiles;
#[cfg(feature = "aws_databrew")]
pub mod databrew;
#[cfg(feature = "aws_datapipeline")]
pub mod datapipeline;
#[cfg(feature = "aws_datasync")]
pub mod datasync;
#[cfg(feature = "aws_datazone")]
pub mod datazone;
#[cfg(feature = "aws_dax")]
pub mod dax;
#[cfg(feature = "aws_deadline")]
pub mod deadline;
#[cfg(feature = "aws_detective")]
pub mod detective;
#[cfg(feature = "aws_devopsagent")]
pub mod devopsagent;
#[cfg(feature = "aws_devopsguru")]
pub mod devopsguru;
#[cfg(feature = "aws_directoryservice")]
pub mod directoryservice;
#[cfg(feature = "aws_dlm")]
pub mod dlm;
#[cfg(feature = "aws_dms")]
pub mod dms;
#[cfg(feature = "aws_docdb")]
pub mod docdb;
#[cfg(feature = "aws_docdbelastic")]
pub mod docdbelastic;
#[cfg(feature = "aws_dsql")]
pub mod dsql;
#[cfg(feature = "aws_dynamodb")]
pub mod dynamodb;
#[cfg(feature = "aws_ec2")]
pub mod ec2;
#[cfg(feature = "aws_ecr")]
pub mod ecr;
#[cfg(feature = "aws_ecs")]
pub mod ecs;
#[cfg(feature = "aws_efs")]
pub mod efs;
#[cfg(feature = "aws_eks")]
pub mod eks;
#[cfg(feature = "aws_elasticache")]
pub mod elasticache;
#[cfg(feature = "aws_elasticbeanstalk")]
pub mod elasticbeanstalk;
#[cfg(feature = "aws_elasticloadbalancing")]
pub mod elasticloadbalancing;
#[cfg(feature = "aws_elasticloadbalancingv2")]
pub mod elasticloadbalancingv2;
#[cfg(feature = "aws_elasticsearch")]
pub mod elasticsearch;
#[cfg(feature = "aws_emr")]
pub mod emr;
#[cfg(feature = "aws_emrcontainers")]
pub mod emrcontainers;
#[cfg(feature = "aws_emrserverless")]
pub mod emrserverless;
#[cfg(feature = "aws_entityresolution")]
pub mod entityresolution;
#[cfg(feature = "aws_events")]
pub mod events;
#[cfg(feature = "aws_eventschemas")]
pub mod eventschemas;
#[cfg(feature = "aws_evidently")]
pub mod evidently;
#[cfg(feature = "aws_evs")]
pub mod evs;
#[cfg(feature = "aws_finspace")]
pub mod finspace;
#[cfg(feature = "aws_fis")]
pub mod fis;
#[cfg(feature = "aws_fms")]
pub mod fms;
#[cfg(feature = "aws_forecast")]
pub mod forecast;
#[cfg(feature = "aws_frauddetector")]
pub mod frauddetector;
#[cfg(feature = "aws_fsx")]
pub mod fsx;
#[cfg(feature = "aws_gamelift")]
pub mod gamelift;
#[cfg(feature = "aws_globalaccelerator")]
pub mod globalaccelerator;
#[cfg(feature = "aws_glue")]
pub mod glue;
#[cfg(feature = "aws_grafana")]
pub mod grafana;
#[cfg(feature = "aws_greengrass")]
pub mod greengrass;
#[cfg(feature = "aws_greengrassv2")]
pub mod greengrassv2;
#[cfg(feature = "aws_groundstation")]
pub mod groundstation;
#[cfg(feature = "aws_guardduty")]
pub mod guardduty;
#[cfg(feature = "aws_healthimaging")]
pub mod healthimaging;
#[cfg(feature = "aws_healthlake")]
pub mod healthlake;
#[cfg(feature = "aws_iam")]
pub mod iam;
#[cfg(feature = "aws_identitystore")]
pub mod identitystore;
#[cfg(feature = "aws_imagebuilder")]
pub mod imagebuilder;
#[cfg(feature = "aws_inspector")]
pub mod inspector;
#[cfg(feature = "aws_inspectorv2")]
pub mod inspectorv2;
#[cfg(feature = "aws_internetmonitor")]
pub mod internetmonitor;
#[cfg(feature = "aws_invoicing")]
pub mod invoicing;
#[cfg(feature = "aws_iot")]
pub mod iot;
#[cfg(feature = "aws_iotanalytics")]
pub mod iotanalytics;
#[cfg(feature = "aws_iotcoredeviceadvisor")]
pub mod iotcoredeviceadvisor;
#[cfg(feature = "aws_iotevents")]
pub mod iotevents;
#[cfg(feature = "aws_iotfleetwise")]
pub mod iotfleetwise;
#[cfg(feature = "aws_iotsitewise")]
pub mod iotsitewise;
#[cfg(feature = "aws_iotthingsgraph")]
pub mod iotthingsgraph;
#[cfg(feature = "aws_iottwinmaker")]
pub mod iottwinmaker;
#[cfg(feature = "aws_iotwireless")]
pub mod iotwireless;
#[cfg(feature = "aws_ivs")]
pub mod ivs;
#[cfg(feature = "aws_ivschat")]
pub mod ivschat;
#[cfg(feature = "aws_kafkaconnect")]
pub mod kafkaconnect;
#[cfg(feature = "aws_kendra")]
pub mod kendra;
#[cfg(feature = "aws_kendraranking")]
pub mod kendraranking;
#[cfg(feature = "aws_kinesis")]
pub mod kinesis;
#[cfg(feature = "aws_kinesisanalytics")]
pub mod kinesisanalytics;
#[cfg(feature = "aws_kinesisanalyticsv2")]
pub mod kinesisanalyticsv2;
#[cfg(feature = "aws_kinesisfirehose")]
pub mod kinesisfirehose;
#[cfg(feature = "aws_kinesisvideo")]
pub mod kinesisvideo;
#[cfg(feature = "aws_kms")]
pub mod kms;
#[cfg(feature = "aws_lakeformation")]
pub mod lakeformation;
#[cfg(feature = "aws_lambda")]
pub mod lambda;
#[cfg(feature = "aws_launchwizard")]
pub mod launchwizard;
#[cfg(feature = "aws_lex")]
pub mod lex;
#[cfg(feature = "aws_licensemanager")]
pub mod licensemanager;
#[cfg(feature = "aws_lightsail")]
pub mod lightsail;
#[cfg(feature = "aws_location")]
pub mod location;
#[cfg(feature = "aws_logs")]
pub mod logs;
#[cfg(feature = "aws_lookoutequipment")]
pub mod lookoutequipment;
#[cfg(feature = "aws_lookoutvision")]
pub mod lookoutvision;
#[cfg(feature = "aws_m2")]
pub mod m2;
#[cfg(feature = "aws_macie")]
pub mod macie;
#[cfg(feature = "aws_managedblockchain")]
pub mod managedblockchain;
#[cfg(feature = "aws_mediaconnect")]
pub mod mediaconnect;
#[cfg(feature = "aws_mediaconvert")]
pub mod mediaconvert;
#[cfg(feature = "aws_medialive")]
pub mod medialive;
#[cfg(feature = "aws_mediapackage")]
pub mod mediapackage;
#[cfg(feature = "aws_mediapackagev2")]
pub mod mediapackagev2;
#[cfg(feature = "aws_mediastore")]
pub mod mediastore;
#[cfg(feature = "aws_mediatailor")]
pub mod mediatailor;
#[cfg(feature = "aws_memorydb")]
pub mod memorydb;
#[cfg(feature = "aws_mpa")]
pub mod mpa;
#[cfg(feature = "aws_msk")]
pub mod msk;
#[cfg(feature = "aws_mwaa")]
pub mod mwaa;
#[cfg(feature = "aws_mwaaserverless")]
pub mod mwaaserverless;
#[cfg(feature = "aws_neptune")]
pub mod neptune;
#[cfg(feature = "aws_neptunegraph")]
pub mod neptunegraph;
#[cfg(feature = "aws_networkfirewall")]
pub mod networkfirewall;
#[cfg(feature = "aws_networkmanager")]
pub mod networkmanager;
#[cfg(feature = "aws_notifications")]
pub mod notifications;
#[cfg(feature = "aws_notificationscontacts")]
pub mod notificationscontacts;
#[cfg(feature = "aws_oam")]
pub mod oam;
#[cfg(feature = "aws_observabilityadmin")]
pub mod observabilityadmin;
#[cfg(feature = "aws_odb")]
pub mod odb;
#[cfg(feature = "aws_omics")]
pub mod omics;
#[cfg(feature = "aws_opensearchserverless")]
pub mod opensearchserverless;
#[cfg(feature = "aws_opensearchservice")]
pub mod opensearchservice;
#[cfg(feature = "aws_opsworks")]
pub mod opsworks;
#[cfg(feature = "aws_organizations")]
pub mod organizations;
#[cfg(feature = "aws_osis")]
pub mod osis;
#[cfg(feature = "aws_panorama")]
pub mod panorama;
#[cfg(feature = "aws_paymentcryptography")]
pub mod paymentcryptography;
#[cfg(feature = "aws_pcaconnectorad")]
pub mod pcaconnectorad;
#[cfg(feature = "aws_pcaconnectorscep")]
pub mod pcaconnectorscep;
#[cfg(feature = "aws_pcs")]
pub mod pcs;
#[cfg(feature = "aws_personalize")]
pub mod personalize;
#[cfg(feature = "aws_pinpoint")]
pub mod pinpoint;
#[cfg(feature = "aws_pinpointemail")]
pub mod pinpointemail;
#[cfg(feature = "aws_pipes")]
pub mod pipes;
#[cfg(feature = "aws_proton")]
pub mod proton;
#[cfg(feature = "aws_qbusiness")]
pub mod qbusiness;
#[cfg(feature = "aws_qldb")]
pub mod qldb;
#[cfg(feature = "aws_quicksight")]
pub mod quicksight;
#[cfg(feature = "aws_ram")]
pub mod ram;
#[cfg(feature = "aws_rbin")]
pub mod rbin;
#[cfg(feature = "aws_rds")]
pub mod rds;
#[cfg(feature = "aws_redshift")]
pub mod redshift;
#[cfg(feature = "aws_redshiftserverless")]
pub mod redshiftserverless;
#[cfg(feature = "aws_refactorspaces")]
pub mod refactorspaces;
#[cfg(feature = "aws_rekognition")]
pub mod rekognition;
#[cfg(feature = "aws_resiliencehub")]
pub mod resiliencehub;
#[cfg(feature = "aws_resourceexplorer2")]
pub mod resourceexplorer2;
#[cfg(feature = "aws_resourcegroups")]
pub mod resourcegroups;
#[cfg(feature = "aws_robomaker")]
pub mod robomaker;
#[cfg(feature = "aws_rolesanywhere")]
pub mod rolesanywhere;
#[cfg(feature = "aws_route53")]
pub mod route53;
#[cfg(feature = "aws_route53profiles")]
pub mod route53profiles;
#[cfg(feature = "aws_route53recoverycontrol")]
pub mod route53recoverycontrol;
#[cfg(feature = "aws_route53recoveryreadiness")]
pub mod route53recoveryreadiness;
#[cfg(feature = "aws_route53resolver")]
pub mod route53resolver;
#[cfg(feature = "aws_rtbfabric")]
pub mod rtbfabric;
#[cfg(feature = "aws_rum")]
pub mod rum;
#[cfg(feature = "aws_s3")]
pub mod s3;
#[cfg(feature = "aws_s3express")]
pub mod s3express;
#[cfg(feature = "aws_s3objectlambda")]
pub mod s3objectlambda;
#[cfg(feature = "aws_s3outposts")]
pub mod s3outposts;
#[cfg(feature = "aws_s3tables")]
pub mod s3tables;
#[cfg(feature = "aws_s3vectors")]
pub mod s3vectors;
#[cfg(feature = "aws_sagemaker")]
pub mod sagemaker;
#[cfg(feature = "aws_scheduler")]
pub mod scheduler;
#[cfg(feature = "aws_sdb")]
pub mod sdb;
#[cfg(feature = "aws_secretsmanager")]
pub mod secretsmanager;
#[cfg(feature = "aws_securityhub")]
pub mod securityhub;
#[cfg(feature = "aws_securitylake")]
pub mod securitylake;
#[cfg(feature = "aws_servicecatalog")]
pub mod servicecatalog;
#[cfg(feature = "aws_servicecatalogappregistry")]
pub mod servicecatalogappregistry;
#[cfg(feature = "aws_servicediscovery")]
pub mod servicediscovery;
#[cfg(feature = "aws_ses")]
pub mod ses;
#[cfg(feature = "aws_shield")]
pub mod shield;
#[cfg(feature = "aws_signer")]
pub mod signer;
#[cfg(feature = "aws_simspaceweaver")]
pub mod simspaceweaver;
#[cfg(feature = "aws_smsvoice")]
pub mod smsvoice;
#[cfg(feature = "aws_sns")]
pub mod sns;
#[cfg(feature = "aws_sqs")]
pub mod sqs;
#[cfg(feature = "aws_ssm")]
pub mod ssm;
#[cfg(feature = "aws_ssmcontacts")]
pub mod ssmcontacts;
#[cfg(feature = "aws_ssmguiconnect")]
pub mod ssmguiconnect;
#[cfg(feature = "aws_ssmincidents")]
pub mod ssmincidents;
#[cfg(feature = "aws_ssmquicksetup")]
pub mod ssmquicksetup;
#[cfg(feature = "aws_sso")]
pub mod sso;
#[cfg(feature = "aws_stepfunctions")]
pub mod stepfunctions;
#[cfg(feature = "aws_supportapp")]
pub mod supportapp;
#[cfg(feature = "aws_synthetics")]
pub mod synthetics;
#[cfg(feature = "aws_systemsmanagersap")]
pub mod systemsmanagersap;
#[cfg(feature = "aws_timestream")]
pub mod timestream;
#[cfg(feature = "aws_transfer")]
pub mod transfer;
#[cfg(feature = "aws_verifiedpermissions")]
pub mod verifiedpermissions;
#[cfg(feature = "aws_voiceid")]
pub mod voiceid;
#[cfg(feature = "aws_vpclattice")]
pub mod vpclattice;
#[cfg(feature = "aws_waf")]
pub mod waf;
#[cfg(feature = "aws_wafregional")]
pub mod wafregional;
#[cfg(feature = "aws_wafv2")]
pub mod wafv2;
#[cfg(feature = "aws_wisdom")]
pub mod wisdom;
#[cfg(feature = "aws_workspaces")]
pub mod workspaces;
#[cfg(feature = "aws_workspacesinstances")]
pub mod workspacesinstances;
#[cfg(feature = "aws_workspacesthinclient")]
pub mod workspacesthinclient;
#[cfg(feature = "aws_workspacesweb")]
pub mod workspacesweb;
#[cfg(feature = "aws_xray")]
pub mod xray;
