# This file is generated by `manager pg-ephemeral sync`.
# Do not edit manually.

Gem::Specification.new do |spec|
  spec.name          = 'pg-ephemeral'
  spec.version       = '0.0.1.pre2'
  spec.authors       = ['Markus Schirp']
  spec.email         = ['mbj@schirp-dso.com']

  spec.summary       = 'Ruby wrapper for pg-ephemeral PostgreSQL testing utility'
  spec.description   = 'Provides ephemeral PostgreSQL instances for testing, wrapping the pg-ephemeral project binary'
  spec.homepage      = 'https://github.com/mbj/mrs/tree/main/pg-ephemeral'
  spec.license       = 'MIT'
  spec.required_ruby_version = '>= 3.2'

  spec.metadata['homepage_uri'] = spec.homepage
  spec.metadata['source_code_uri'] = 'https://github.com/mbj/mrs'
  spec.metadata['changelog_uri'] = 'https://github.com/mbj/mrs/blob/main/pg-ephemeral/CHANGELOG.md'

  if ENV['PG_EPHEMERAL_GEMSPEC_CONFIG']
    require 'json'
    config = JSON.parse(ENV.fetch('PG_EPHEMERAL_GEMSPEC_CONFIG'))
    spec.platform = Gem::Platform.new(config.fetch('ruby_platform'))
    spec.files    = Dir['lib/**/*'] + config.fetch('bin_files') + ['LICENSE.txt']
  else
    spec.files = Dir['lib/**/*', 'bin/**/*', 'README.md', 'LICENSE.txt']
    spec.add_development_dependency 'mutant-rspec', '~> 0.14.2'
    spec.add_development_dependency 'rspec', '~> 3.0'
  end

  spec.require_paths = ['lib']
  spec.add_dependency 'pg', '~> 1.5'
end
